# Generated by Django 3.0 on 2022-06-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=120)),
                ('sage', models.IntegerField()),
                ('semail', models.EmailField(max_length=120)),
            ],
        ),
    ]
